---
  # Build WordPress and push to GHCR.
  name: Build WordPress container
  
  on:
    - push
  
  jobs:
    build:
      name: Build Wordpress image
      runs-on: ubuntu-24.04
      permissions:
        contents: read
        packages: write
      env:
        # Image registry and registry user are set in the steps below.
        IMAGE_REGISTRY: ""
        REGISTRY_PROVIDER: ghcr.io
        REGISTRY_USER: ""
        REGISTRY_PASSWORD: ${{ github.token }}
  
      steps:
  
        - name: Clone the repository
          uses: actions/checkout@v3
  
        # Use Nushell for all scripts.
        - uses: hustcer/setup-nu@v3
          with:
            # Don't use 0.90 here, as it would be a float number and would be converted to 0.9
            # you can use v0.90/0.90.0 or '0.90'
            version: "0.104.1"
  
        # The repository owner needs to be lowercase.
        - name: Set environment variables
          shell: nu {0}
          run: |
            let owner = ($env.GITHUB_REPOSITORY_OWNER | str downcase)
            $"REGISTRY_USER=($owner)\n" | save --append $env.GITHUB_ENV
            $"IMAGE_REGISTRY=($env.REGISTRY_PROVIDER)/($owner)\n" | save --append $env.GITHUB_ENV
  
        ################################################################################
        # Production
        ################################################################################
        - name: Build Wordpress production image
          id: build-prod-image
          env:
            ENVIRONMENT: prod
          shell: nu {0}
          run: |
            cd wordpress
            ./build.nu
  
        # Example to push to GHCR: https://github.com/redhat-actions/push-to-registry/blob/main/.github/workflows/ghcr-push.yaml
        - name: Push prod image to GitHub Container Repository
          id: push-to-ghcr-prod
          uses: redhat-actions/push-to-registry@v2
          with:
            registry: ${{ env.IMAGE_REGISTRY }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            image: ${{ steps.build-prod-image.outputs.image }}
            tags: ${{ steps.build-prod-image.outputs.tags }}
  
        - name: Print image URL (prod)
          run: echo "Production image pushed to ${{ steps.push-to-ghcr-prod.outputs.registry-paths }}"
  
        ################################################################################
        # Debug/development
        ################################################################################
        - name: Build debug image
          id: build-debug-image
          env:
            ENVIRONMENT: debug
          shell: nu {0}
          run: |
            cd wordpress
            ./build.nu
  
        # Example to push to GHCR: https://github.com/redhat-actions/push-to-registry/blob/main/.github/workflows/ghcr-push.yaml
        - name: Push debug image to GitHub Container Repository
          id: push-to-ghcr-debug
          uses: redhat-actions/push-to-registry@v2
          with:
            registry: ${{ env.IMAGE_REGISTRY }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            image: ${{ steps.build-debug-image.outputs.image }}
            tags: ${{ steps.build-debug-image.outputs.tags }}
  
        - name: Print image URL (debug)
          run: echo "Debug image pushed to ${{ steps.push-to-ghcr-debug.outputs.registry-paths }}"
  